version: "3.9"
services:
  postgres15:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres15:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres15
    entrypoint: [ "/app/wait-for.sh", "postgres15:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]